# Generated by Django 5.0.6 on 2024-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='jobs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
